import { Product, DeliveryZone, LensOption } from '@/types';

export const lensOptionsConfig: LensOption[] = [
  {
    id: "monture-seule",
    name: "Monture Seule (Verres de présentation)",
    price: 0,
    description: "Livrée avec ses verres de démonstration d'origine, prête pour montage chez votre opticien.",
  },
  {
    id: "anti-lumiere-bleue",
    name: "Traitement Filtre Écran & Anti-Lumière Bleue",
    price: 5000,
    description: "Protection 420nm idéale pour ordinateur, smartphone et éclairage LED. Réduit la fatigue oculaire.",
  },
  {
    id: "anti-reflet-uv",
    name: "Verres Anti-Reflet Premium UV400",
    price: 7000,
    description: "Traitement hydrophobe et oléophobe réduisant les reflets de conduite et les éblouissements.",
  },
  {
    id: "verres-correcteurs",
    name: "Montage Verres Correcteurs sur Ordonnance",
    price: 15000,
    description: "Verres unifocaux adaptés à votre correction ophtalmologique (ordonnance transmise sur WhatsApp).",
  },
];

export const siteConfig = {
  name: "Gémeaux Optique",
  shortName: "Gémeaux Optique",
  tagline: "Lunetterie & Solaires Haute Précision à Dakar",
  slogan: "L'élégance du regard, la précision de la vision.",
  description: "Boutique d'optique et lunettes de soleil de référence à Dakar. Montures haute couture, solaires tendance, verres protecteurs anti-lumière bleue et montage optique sur mesure. Livraison express à Dakar et partout au Sénégal.",
  url: "https://gemeauxoptique.sn",
  email: "contact@gemeauxoptique.sn",
  phonePrimary: "+221 76 282 02 91",
  phoneSecondary: "+221 70 778 99 08",
  whatsappMain: "+221707789908",
  whatsappRaw: "221707789908",
  location: {
    city: "Dakar",
    country: "Sénégal",
    address: "Dakar, Sénégal — Service d'essayage & Livraison express à domicile",
    hours: "Lundi au Samedi : 08h30 - 20h30 · Service WhatsApp 7j/7",
  },
  social: {
    facebook: "https://facebook.com/profile.php?id=gemeauxoptique",
    instagram: "https://instagram.com/gemeaux_optique",
  },
  payments: ["Wave", "Orange Money", "Free Money", "Espèces à la livraison"],

  deliveryZones: [
    { area: "Dakar Centre (Plateau, Médina, Fann, Point E)", price: 1500, timeframe: "2 à 4h chrono" },
    { area: "Grand Dakar (Almadies, Ngor, Ouakam, Mermoz, Yoff)", price: 2000, timeframe: "Dans la journée" },
    { area: "Banlieue (Pikine, Guédiawaye, Keur Massar, Rufisque)", price: 2500, timeframe: "24h chrono" },
    { area: "Régions du Sénégal (Thiès, Saint-Louis, Mbour, Touba...)", price: 3500, timeframe: "Expédition GP / La Poste 24-48h" },
  ] as DeliveryZone[],

  products: [
    {
      id: "solaire-fendi-gold-black",
      name: "Solaires Haute Couture Fendi Armor Gold",
      brand: "Fendi Roma",
      category: "solaires",
      shape: "Carrée / Rectangulaire",
      material: "Combiné Acétate & Métal",
      price: 10000,
      originalPrice: 15000,
      image: "/images/products/solaire-fendi-gold-black.jpg",
      badge: "Best-Seller Dakar",
      colors: ["Monture Or Brossé & Branches Noires"],
      gender: "Unisexe",
      bridgeWidth: "56-18-140",
      isPopular: true,
      isNewArrival: true,
      description: "Monture solaire géométrique carrée avec charnières or sculptées Fendi et verres dégradés bronze anti-éblouissement. Un style affirmé pour le soleil dakarois.",
      features: [
        "Verres dégradés UV400 haute protection",
        "Armature métallique dorée traitée anti-oxydation",
        "Branches en acétate noir poli avec logo gravé",
        "Plaquettes nasales ajustables en silicone souple",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "solaire-fendi-hexagone-blue",
      name: "Solaires Hexagonales Titanium Fendi Bleu Océan",
      brand: "Fendi Roma",
      category: "solaires",
      shape: "Hexagonale / Géométrique",
      material: "Combiné Acétate & Métal",
      price: 10000,
      originalPrice: 15000,
      image: "/images/products/solaire-fendi-hexagone-blue.jpg",
      badge: "Tendance 2026",
      colors: ["Argent & Acétate Gris Nuit", "Verres Dégradés Bleu Océan"],
      gender: "Unisexe",
      bridgeWidth: "54-19-145",
      isPopular: true,
      isNewArrival: true,
      description: "Lignes octogonales audacieuses combinant cerclage en acétate biseauté et structure métallique chromée. Verres bi-dégradés bleu vers ambre.",
      features: [
        "Verres polarisants UV400 catégorie 3",
        "Pont double renforcé et branches ergonomiques",
        "Finition bicolore argent satiné et acétate translucide",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "monture-burberry-anti-lumiere",
      name: "Monture Écran Burberry Oversize Acétate Noir",
      brand: "Burberry London",
      category: "anti-lumiere-bleue",
      shape: "Carrée / Rectangulaire",
      material: "Acétate de Cellulose",
      price: 12000,
      originalPrice: 18000,
      image: "/images/products/monture-burberry-anti-lumiere.jpg",
      badge: "Protection Écran 420nm",
      colors: ["Noir Laqué Profond", "Médaillon Or"],
      gender: "Unisexe",
      bridgeWidth: "55-17-145",
      isPopular: true,
      isNewArrival: true,
      description: "Monture carrée oversize en acétate dense avec médaillon doré iconique Burberry sur les branches. Spécialement conçue pour le confort sur écrans et réunions prolongées.",
      features: [
        "Verres de filtration anti-lumière bleue 420nm inclus",
        "Acétate de cellulose italien poli à la main",
        "Charnières flexibles 5 barillets haute résistance",
        "Compatible tous types de verres correcteurs",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "monture-burberry-ecaille-tortoise",
      name: "Monture Burberry Écaille Havane Papillon",
      brand: "Burberry London",
      category: "anti-lumiere-bleue",
      shape: "Cat-Eye / Papillon",
      material: "Acétate de Cellulose",
      price: 12000,
      originalPrice: 18000,
      image: "/images/products/monture-burberry-ecaille.jpg",
      badge: "Chic & Rétro",
      colors: ["Écaille Ambrée Havane"],
      gender: "Femme",
      bridgeWidth: "53-18-142",
      isPopular: true,
      description: "Sublime motif écaille ambrée aux nuances chaudes. Galbe papillon adoucissant les traits du visage et verres traités anti-reflet.",
      features: [
        "Finition écaille brillante sans transfert de couleur",
        "Galbe rehaussant le regard et pommettes",
        "Traitement anti-rayures multi-couches",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "solaire-aviateur-gold-noir",
      name: "Solaires Hexagonales Aviateur Gold Minimalist",
      brand: "Gémeaux Signature",
      category: "solaires",
      shape: "Aviateur / Pilote",
      material: "Métal Doré / Titane",
      price: 10000,
      image: "/images/products/solaire-aviateur-gold-noir.jpg",
      badge: "Légèreté Absolue",
      colors: ["Monture Or Poli & Verres Noirs"],
      gender: "Homme",
      bridgeWidth: "57-16-145",
      isPopular: true,
      description: "Réinterprétation moderne de l'aviateur classique avec un contour géométrique hexagonal. Verres noirs anti-reflet face arrière.",
      features: [
        "Structure ultra-légère en alliage métal doré",
        "Manchons en acétate noir confort derrière les oreilles",
        "Protection 100% UVA & UVB",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "monture-ronde-acetate-black",
      name: "Monture Ronde Studio Intellectuelle",
      brand: "Gémeaux Signature",
      category: "optiques-vue",
      shape: "Ronde / Ovale",
      material: "Acétate de Cellulose",
      price: 10000,
      image: "/images/products/monture-ronde-acetate-black.jpg",
      badge: "Iconique & Intemporel",
      colors: ["Noir Mat", "Noir Brillant"],
      gender: "Unisexe",
      bridgeWidth: "48-21-145",
      isPopular: true,
      description: "Le modèle culte à cerclage rond façon créateur parisien. Pont en clé de serrure offrant un maintien parfait sur le nez.",
      features: [
        "Pont en trou de serrure rétro très confortable",
        "Acétate noir dense hypoallergénique",
        "Idéale pour fortes corrections myopiques ou astigmates",
      ],
      lensOptions: lensOptionsConfig,
    },
    {
      id: "monture-pilote-navy-titanium",
      name: "Monture Clubmaster Demi-Cerclée Acier & Bleu Nuit",
      brand: "Gémeaux Signature",
      category: "optiques-vue",
      shape: "Carrée / Rectangulaire",
      material: "Combiné Acétate & Métal",
      price: 11000,
      image: "/images/products/monture-pilote-navy.jpg",
      badge: "Élégance Business",
      colors: ["Bleu Nuit & Métal Argenté"],
      gender: "Homme",
      bridgeWidth: "53-19-145",
      description: "Monture semi-cerclée très distinguée pour cadres et professionnels. Structure en acier brossé alliant finesse et robustesse.",
      features: [
        "Ligne supérieure en acétate texturé",
        "Structure inférieure en fil nylon haute tension",
        "Charnières à ressort Flex pour ouverture sans déformation",
      ],
      lensOptions: lensOptionsConfig,
    },
  ] as Product[],

  features: [
    {
      title: "Verres Anti-Lumière Bleue",
      desc: "Filtration 420nm certifiée pour soulager vos yeux des écrans, téléphones et insomnies.",
      icon: "ShieldCheck",
    },
    {
      title: "Solaires Haute Couture 10.000 F",
      desc: "Les plus belles inspirations Fendi, Burberry et créateurs au tarif le plus juste de Dakar.",
      icon: "SunMedium",
    },
    {
      title: "Montage sur Ordonnance",
      desc: "Envoyez simplement la photo de votre ordonnance sur WhatsApp pour vos verres correcteurs.",
      icon: "FileText",
    },
    {
      title: "Livraison Express & Essayage Dakar",
      desc: "Recevez vos montures en 2 à 4 heures à domicile ou au bureau avec paiement Wave / OM.",
      icon: "Truck",
    },
  ],

  testimonials: [
    {
      name: "Mamadou L. Diallo",
      role: "Développeur & Télétravailleur",
      location: "Almadies, Dakar",
      comment: "Je passais 10h par jour sur écran avec de gros maux de tête le soir. Depuis que j'ai pris la monture Burberry avec verres anti-lumière bleue chez Gémeaux Optique, la différence est immédiate. Livré en 3h aux Almadies !",
      rating: 5,
    },
    {
      name: "Aïssatou Ndiaye",
      role: "Responsable Marketing",
      location: "Plateau, Dakar",
      comment: "La solaire Fendi dorée est juste sublime, les finitions sont de très haute qualité pour 10.000 F CFA. L'équipe m'a envoyé des vidéos de la monture sous tous les angles sur WhatsApp avant validation.",
      rating: 5,
    },
    {
      name: "Dr. Ousmane Kane",
      role: "Consultant",
      location: "Point E, Dakar",
      comment: "J'ai fait monter mes verres correcteurs sur une monture ronde en envoyant mon ordonnance sur WhatsApp. Travail net, centrage parfait et étui rigide fourni.",
      rating: 5,
    },
  ],

  faqs: [
    {
      question: "Comment commander mes verres de vue avec mon ordonnance ?",
      answer: "C'est très simple : choisissez votre monture préférée, sélectionnez l'option 'Verres correcteurs' ou cliquez sur le bouton WhatsApp pour nous envoyer une photo de votre ordonnance médicale. Notre équipe vérifie vos dioptries et prépare vos verres sur mesure.",
    },
    {
      question: "Quelle est l'efficacité des verres anti-lumière bleue Gémeaux ?",
      answer: "Nos verres bloquent jusqu'à 90% des rayonnements nocifs de la lumière bleue (spectre 380-450nm) émis par les ordinateurs, téléphones et tablettes. Ils réduisent l'éblouissement, la sécheresse oculaire et favorisent un meilleur endormissement.",
    },
    {
      question: "Quels sont les délais de livraison à Dakar et dans les régions ?",
      answer: "Sur Dakar (Plateau, Almadies, Mermoz, Yoff, etc.), nous livrons dans la journée en 2 à 4h chrono par coursier dédié. Pour les régions (Thiès, Saint-Louis, Mbour, Touba...), l'expédition s'effectue sous 24 à 48h.",
    },
    {
      question: "Puis-je payer par Wave ou Orange Money à la livraison ?",
      answer: "Oui ! Vous pouvez régler à la livraison en espèces, par Wave ou via Orange Money après avoir réceptionné et vérifié vos lunettes.",
    },
  ],
};
